version: "3.8" # Ensure you're using a version compatible with Swarm

services:
  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  tunemate-be:
    image: ghcr.io/potenday-tunemate/tunemate-be:${GIT_COMMIT_HASH:-latest}
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - "8080:8080"
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
volumes:
  db_data:
