version: '3.8'

services:
  db:
    image: mariadb:10.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  tunemate-be:
    build: .
    container_name: tunemate-be
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
